# Generated by Django 5.2.1 on 2026-04-25 17:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(default='clear_for_planning', max_length=64)),
                ('categories', models.JSONField(default=list)),
                ('required_approvals', models.JSONField(default=list)),
                ('missing_information', models.JSONField(default=list)),
                ('warning', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_assessments', to='projects.experimentquestion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
