# Generated by Django 5.2.1 on 2026-04-25 17:42

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='ReviewAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_key', models.CharField(max_length=64)),
                ('target_model', models.CharField(blank=True, max_length=64)),
                ('target_id', models.UUIDField(null=True)),
                ('correction_type', models.CharField(max_length=64)),
                ('original_text', models.TextField(blank=True)),
                ('corrected_text', models.TextField()),
                ('rationale', models.TextField(blank=True)),
                ('severity', models.CharField(max_length=32)),
                ('tags', models.JSONField(default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedbackExample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(max_length=64)),
                ('experiment_type', models.CharField(max_length=128)),
                ('input_context', models.JSONField(default=dict)),
                ('bad_output', models.TextField()),
                ('corrected_output', models.TextField()),
                ('lesson', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536, null=True)),
                ('approved_for_reuse', models.BooleanField(default=False)),
                ('source_annotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='feedback.reviewannotation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='in_progress', max_length=32)),
                ('overall_rating', models.IntegerField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.experimentplan')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='reviewannotation',
            name='review_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='feedback.reviewsession'),
        ),
    ]
