# Generated by Django 5.2.1 on 2026-04-25 17:42

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='LiteratureQcRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='queued', max_length=32)),
                ('novelty_signal', models.CharField(blank=True, choices=[('not_found', 'Not found'), ('similar_work_exists', 'Similar work exists'), ('exact_match_found', 'Exact match found'), ('inconclusive', 'Inconclusive')], max_length=32)),
                ('confidence', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('summary', models.TextField(blank=True)),
                ('query_plan', models.JSONField(default=dict)),
                ('scoring_breakdown', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_runs', to='projects.experimentquestion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=64)),
                ('title', models.TextField()),
                ('authors', models.JSONField(default=list)),
                ('year', models.IntegerField(null=True)),
                ('abstract', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('doi', models.CharField(blank=True, max_length=255)),
                ('pmid', models.CharField(blank=True, max_length=64)),
                ('protocol_id', models.CharField(blank=True, max_length=255)),
                ('relevance_score', models.DecimalField(decimal_places=4, max_digits=5, null=True)),
                ('why_relevant', models.TextField(blank=True)),
                ('match_json', models.JSONField(default=dict)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536, null=True)),
                ('qc_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='literature.literatureqcrun')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
