# Generated by Django 5.2.1 on 2026-04-25 17:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('literature', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(default='draft', max_length=32)),
                ('version', models.IntegerField(default=1)),
                ('executive_summary', models.TextField(blank=True)),
                ('plan_json', models.JSONField(default=dict)),
                ('estimated_budget_min', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('estimated_budget_max', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('estimated_duration_weeks_min', models.IntegerField(null=True)),
                ('estimated_duration_weeks_max', models.IntegerField(null=True)),
                ('scientist_review_status', models.CharField(default='required', max_length=32)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('qc_run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='literature.literatureqcrun')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.experimentquestion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('assumptions', models.TextField(blank=True)),
                ('confidence', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_lines', to='planning.experimentplan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=64)),
                ('role', models.TextField(blank=True)),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('catalog_number', models.CharField(blank=True, max_length=255)),
                ('catalog_source_url', models.URLField(blank=True)),
                ('quantity', models.CharField(blank=True, max_length=128)),
                ('estimated_unit_cost', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('estimated_total_cost', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('lead_time_days_min', models.IntegerField(null=True)),
                ('lead_time_days_max', models.IntegerField(null=True)),
                ('storage_conditions', models.CharField(blank=True, max_length=255)),
                ('confidence', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('needs_supplier_verification', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='planning.experimentplan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('content_markdown', models.TextField(blank=True)),
                ('content_json', models.JSONField(default=dict)),
                ('confidence', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('needs_review', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='planning.experimentplan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProtocolStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration_minutes', models.IntegerField(null=True)),
                ('critical_parameters', models.JSONField(default=list)),
                ('equipment', models.JSONField(default=list)),
                ('expected_output', models.TextField(blank=True)),
                ('citations', models.JSONField(default=list)),
                ('safety_notes', models.TextField(blank=True)),
                ('confidence', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocol_steps', to='planning.experimentplan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimelinePhase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('start_week', models.IntegerField()),
                ('end_week', models.IntegerField()),
                ('dependencies', models.JSONField(default=list)),
                ('deliverables', models.JSONField(default=list)),
                ('risks', models.JSONField(default=list)),
                ('parallelizable', models.BooleanField(default=False)),
                ('risk_of_delay', models.CharField(blank=True, max_length=255)),
                ('mitigation', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_phases', to='planning.experimentplan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
